version: "3.9"
services:
  api_github-profile-index:
    container_name: api_github-profile-index
    build:
        context: ./api
        dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    restart: always
    environment:
      - API_HOST_DATABASE=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - database

  frontend_github-profile-index:
    container_name: frontend_github-profile-index
    build:
      context: ./client
      dockerfile: Dockerfile
    command: yarn dev
    restart: always
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"

  database:
    image: postgres
    restart: always
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
